#! /bin/bash

# add postgres sources
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
sudo apt-get install wget ca-certificates
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get upgrade

# install basics
echo "Installing build tools, git, and postgres"
sudo apt-get install build-essential git-core postgresql-9.3-postgis-2.1 libpq-dev autoconf bison libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev
# configure git
echo "Configuring Git"
git config --global user.name "Alex Sleighter"
git config --global user.email "alex.sleighter@gmail.com"

# generate ssh keys
echo "Generating SSH Keys..."
ssh-keygen -t rsa

# display key for copying
cat ~/.ssh/id_rsa.pub
read -p "Copy public key to Github. Press [Enter] to continue"

#install rbenv and ruby-build
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv

# COmment/uncomment next line pairs for distro
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
source ~/.bashrc
# echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
# echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
# source ~/.bash_profile

git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build


# install and set ruby version
rbenv install 2.1.4
rbenv rehash
rbenv global 2.1.4


